import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import PrelineScript from "@/app/components/PrelineLoader"
import { TradesHistoryProvider } from "@/app/components/contexts/TradesHistory"
import Link from "next/link"

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
})
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="w-screen h-screen">
                    <header className="w-full py-5 flex justify-between px-5">
                        <h1 className="text-xl text-center font-semibold">
                            Fx Traders{" "}
                            <span className="text-blue-500 uppercase text-sm font-extrabold">
                                Playground
                            </span>
                        </h1>
                        <div className="flex space-x-3">
                            <Link
                                href={"https://discord.gg/tWutdPwTSU"}
                                className="text-blue-500 font-bold hover:underline"
                            >
                                Join Our Waitlist
                            </Link>
                        </div>
                    </header>
                    <TradesHistoryProvider defaultTrades={[]}>
                        <main className="p-5">{children}</main>
                    </TradesHistoryProvider>
                </div>
            </body>
            <PrelineScript />
        </html>
    )
}
